version: "3.8"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # You can change this, just keep it consistent
      POSTGRES_DB: alemenodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d alemenodb -h 127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    container_name: alemeno_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: alemeno_api
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      # CRITICAL: Inside Docker, the database is no longer on "localhost".
      # It is hosted at the name of the service: "db"
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/alemenodb
      - REDIS_URL=redis://redis:6379/0
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - shared_uploads:/app/uploads

  worker:
    build: .
    container_name: alemeno_worker
    restart: on-failure
    env_file:
      - .env
    command: celery -A app.worker.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/alemenodb
      - REDIS_URL=redis://redis:6379/0
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - shared_uploads:/app/uploads

volumes:
  postgres_data:
  shared_uploads:
